apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: cicd
  labels:
    app: nginx
spec:
  revisionHistoryLimit: 3
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 336481557929.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-front:d0c01892d384200ba648957ca579331499ff8a0a
        ports:
        - containerPort: 80
        