apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "exb-ingress"
  labels:
    app.kubernetes.io/name: "exb-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-03d9d743dcef08178,subnet-0609724dd9cda79f0
    # alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/target-type: ip
 
spec:
  rules:
    - http:
        paths:
          - path: /api/*
            backend:
              serviceName: exb-back-svc
              servicePort: 80
    - http:
        paths:
          - path: /*
            backend:
              serviceName: exb-front-svc
              servicePort: 80  
    