apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /
  newName: /
- name: 336481557929.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-back
  newName: 336481557929.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-back
  newTag: 1fd8909c779fdfa0f38e6d27f1996e20c1f30bf6
- name: 336481557929.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-front
  newName: 336481557929.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-front
  newTag: 349b419475394be13b2e946b7eee74377dcc0d4d

resources:
- ../../resources
