apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /
  newName: /
- name: 336481557929.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-back
  newName: 336481557929.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-back
  newTag: b976b0ce6ce0ca778e79a239ace85e0d05f81a4e
- name: 336481557929.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-front
  newName: 336481557929.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-front
  newTag: 6a143e3742f0493963078356e4db616135ad7ef9

resources:
- ../../resources
